# Generated by Django 5.0.4 on 2024-04-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_cotegory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotegory',
        ),
    ]
